# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1prKZTQfIcllZojCpq3Hew5fHfT-vXXcc
"""

import streamlit as st
import tensorflow as tf
import keras
import requests
import os
from PIL import Image
import numpy as np

# --- PAGE CONFIGURATION ---
st.set_page_config(
    page_title="AI Inference Hub",
    page_icon="⚡",
    layout="centered",
    initial_sidebar_state="collapsed"
)

# --- CAPTIVATING NEON DARK THEME (CUSTOM CSS) ---
# --- CAPTIVATING NEON DARK THEME (CUSTOM CSS) ---
st.markdown("""
    <style>
    /* Main Background & Text Color */
    .stApp {
        background: linear-gradient(135deg, #0d0e15 0%, #1a1c29 100%);
        color: #f0f2f6;
    }
    
    /* Header styling with a vivid gradient */
    .main-title {
        font-size: 3rem !important;
        font-weight: 800 !important;
        background: linear-gradient(45deg, #00f2fe, #4facfe, #0000fe);
        -webkit-background-clip: text;
        -webkit-text-fill-color: transparent;
        text-align: center;
        margin-bottom: 0.5rem;
        letter-spacing: -1px;
    }
    
    .subtitle {
        text-align: center;
        color: #94a3b8;
        font-size: 1.1rem;
        margin-bottom: 3rem;
    }

    /* Glassmorphism containers for file upload and metrics */
    div[data-testid="stFileUploadDropzone"], .stMarkdown div div {
        border-radius: 16px;
    }
    
    /* Custom Card Style for Results */
    .prediction-card {
        background: rgba(255, 255, 255, 0.03);
        border: 1px solid rgba(0, 242, 254, 0.2);
        padding: 24px;
        border-radius: 16px;
        backdrop-filter: blur(12px);
        box-shadow: 0 8px 32px 0 rgba(0, 0, 0, 0.37);
        margin-top: 2rem;
    }
    
    /* Glowing Button Styling */
    .stButton>button {
        width: 100%;
        background: linear-gradient(90deg, #00f2fe 0%, #4facfe 100%) !important;
        color: #0d0e15 !important;
        font-weight: 700 !important;
        border: none !important;
        padding: 12px 24px !important;
        border-radius: 12px !important;
        transition: all 0.3s ease !important;
        box-shadow: 0 4px 15px rgba(0, 242, 254, 0.4);
    }
    
    .stButton>button:hover {
        transform: translateY(-2px);
        box-shadow: 0 6px 20px rgba(0, 242, 254, 0.6);
        color: #ffffff !important;
    }

    /* Progress bar adjustments */
    .stProgress > div > div > div > div {
        background-color: #00f2fe !important;
    }
    </style>
""", unsafe_allow_html=True) # <-- Swapped here
# --- MODEL DOWNLOAD & CACHING ---
MODEL_URL = "https://huggingface.co/Prassh/my_model.keras/resolve/main/my_model.keras"
MODEL_PATH = "my_model.keras"

@st.cache_resource
def load_hf_model():
    """Downloads the Keras model from Hugging Face if not present, then loads it."""
    if not os.path.exists(MODEL_PATH):
        with st.spinner("⚡ Connecting to Hugging Face Hub & fetching your model..."):
            try:
                # Using the direct download 'resolve' endpoint instead of blob view
                response = requests.get(MODEL_URL, stream=True)
                response.raise_for_status()
                with open(MODEL_PATH, "wb") as f:
                    for chunk in response.iter_content(chunk_size=8192):
                        f.write(chunk)
            except Exception as e:
                st.error(f"Failed to fetch model from Hugging Face: {e}")
                return None

    try:
        model = keras.models.load_model(MODEL_PATH)
        return model
    except Exception as e:
        st.error(f"Error loading the Keras file structure: {e}")
        return None

# Initialize Model Loading
model = load_hf_model()

# --- UI LAYOUT ---
st.markdown('<h1 class="main-title">Deep Learning Inference Hub</h1>', unsafe_allow_html=True)
st.markdown('<p class="subtitle">Powered by your custom Keras pipeline hosted on Hugging Face</p>', unsafe_allow_html=True)

if model is not None:
    st.success("Model successfully compiled and cached into local runtime memory.")

    # Input File Selector (Swap this between Image, Text, or CSV depending on your model)
    uploaded_file = st.file_uploader("Drop your target data file here", type=["jpg", "jpeg", "png"])

    if uploaded_file is not None:
        # Displaying selected asset
        image = Image.open(uploaded_file)
        st.image(image, caption="Target Input Asset", use_container_width=True)

        # Trigger button
        if st.button("Run Model Prediction"):
            # --- PLACEHOLDER FOR PREPROCESSING CONFIGURATION ---
            # Adjust these preprocessing arrays to exactly mirror your model's expected shape
            with st.spinner("Processing dimensions..."):
                img_resized = image.resize((224, 224)) # Example target shape
                img_array = np.array(img_resized) / 255.0
                input_tensor = np.expand_dims(img_array, axis=0)

                # Model execution
                predictions = model.predict(input_tensor)

            # --- STUNNING HIGHLIGHT CARD ---
            st.markdown(f"""
                <div class="prediction-card">
                    <h3 style="color: #00f2fe; margin-top: 0;">Inference Metrics</h3>
                    <p style="font-size: 1.1rem; margin-bottom: 8px;">Raw Model Target Output Matrix:</p>
                    <code style="background: rgba(0,0,0,0.4); padding: 8px; display: block; border-radius: 6px; color: #a5f3fc;">
                        {str(predictions[0])}
                    </code>
                </div>
            """, unsafe_allow_html=True)
else:
    st.warning("Awaiting secure connection handshake with Hugging Face repository assets.")
